### ISSUE TITLE
invalid column video

### ISSUE THREAD

**Issue by ziselive** [cdowdy/bolt-html5-video#11] opened 2018-07-26 01:58 UTC
bolt3.5.5
        video:
            type: h5video
After setting contenttypes, the warning is always displayed:
The database needs to be updated/repaired. Go to 'Configuration' > 'Check Database' to do this now. 
Table entries is not the correct schema: invalid column video

**Comment by cdowdy** [comment] 2018-09-13 13:53
@ziselive if you can update to 3.5.6 check and see if this issue https://github.com/bolt/bolt/issues/7382 and this pulll request https://github.com/bolt/bolt/pull/7570 fixed it if you could please

**Comment by cdowdy** [comment] 2018-12-17 17:06
hey @ziselive I'm gonna close this since there's be no action on it in a while and I can't replicate exactly what you've mentioned.  

If this is still an issue for you or anyone else coming across this please don't hesitate to open it back up and comment! I'll work my way through it and see if I can find the root cause.  

Thanks for reporting by the way!

**Closed as completed by cdowdy** 2018-12-17 17:06 UTC
